import * as T from '../vendor/three.module.js';
import {groundHeight,roadClearance,nearestRoad,roadWidth} from './geography.js';
export function lightingAt(hour){const altitude=Math.sin((hour-6)/24*Math.PI*2),day=T.MathUtils.smoothstep(altitude,-.12,.25);return {altitude,day,sun:Math.max(0,altitude)*2.8+.12,ambient:.42+day*1.25};}
export function createAtmosphere(scene,world,renderer,sun,ambient){let hour=16,playing=false;const slider=document.querySelector('#time'),label=document.querySelector('#clock'),play=document.querySelector('#time-play');slider.addEventListener('input',()=>{hour=Number(slider.value);});play.onclick=()=>{playing=!playing;play.textContent=playing?'Ⅱ':'▶';play.setAttribute('aria-pressed',String(playing));};
 const starsGeo=new T.BufferGeometry(),points=[];for(let i=0;i<700;i++){const a=i*2.39996,y=.1+(i%97)/110,r=Math.sqrt(1-y*y);points.push(Math.cos(a)*r*14000,y*14000,Math.sin(a)*r*14000);}starsGeo.setAttribute('position',new T.Float32BufferAttribute(points,3));const stars=new T.Points(starsGeo,new T.PointsMaterial({color:'#fff4d5',size:13,transparent:true,depthWrite:false}));scene.add(stars);
 const lampMaterial=new T.MeshBasicMaterial({color:'#fff0ba'}),poles=new T.Group();scene.add(poles);const lights=[];for(const d of world.destinations.slice(0,5))for(let i=0;i<5;i++){const x=d.arrival[0]+(i-2)*13,z=d.arrival[1]+11;if(roadClearance(x,z)<.5||world.colliders.query(x,z,1).some(c=>Math.abs(x-c.x)<c.w/2&&Math.abs(z-c.z)<c.d/2))continue;const y=groundHeight(x,z),pole=new T.Mesh(new T.CylinderGeometry(.055,.09,4.2,8),new T.MeshLambertMaterial({color:'#646b65'}));pole.position.set(x,y+2.1,z);pole.castShadow=true;poles.add(pole);const bulb=new T.Mesh(new T.SphereGeometry(.24,10,6),lampMaterial);bulb.position.set(x,y+4.2,z);poles.add(bulb);const light=new T.PointLight('#ffce82',0,15,2);light.position.copy(bulb.position);scene.add(light);lights.push(light);
 const bench=new T.Group();for(const h of [.48,.88]){const seat=new T.Mesh(new T.BoxGeometry(2,.13,.6),new T.MeshLambertMaterial({color:'#8b7352'}));seat.position.set(0,h,h>.5?-.25:0);if(h>.5)seat.scale.z=.22;bench.add(seat);}for(const bx of [-.7,.7]){const leg=new T.Mesh(new T.BoxGeometry(.1,.45,.48),new T.MeshLambertMaterial({color:'#555e58'}));leg.position.set(bx,.23,0);bench.add(leg);}bench.position.set(x+1,y,z);poles.add(bench);}
 const topDay=new T.Color('#72b4d9'),topNight=new T.Color('#091329'),bottomDay=new T.Color('#f1ddbd'),bottomNight=new T.Color('#354052'),warm=new T.Color('#eba477');
 return {update(dt,p){if(playing)hour=(hour+dt*.075)%24;slider.value=hour;const h=Math.floor(hour),m=Math.floor(hour%1*60);label.textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');slider.setAttribute('aria-valuetext',label.textContent);const l=lightingAt(hour),twilight=(1-Math.abs(l.altitude)*4);world.sky.material.uniforms.top.value.copy(topNight).lerp(topDay,l.day);world.sky.material.uniforms.bottom.value.copy(bottomNight).lerp(bottomDay,l.day).lerp(warm,Math.max(0,twilight)*.35);scene.fog.color.copy(world.sky.material.uniforms.bottom.value);ambient.intensity=l.ambient;sun.intensity=l.sun;sun.color.set(l.altitude<.3?'#ffd2a0':'#fff0d4');sun.position.copy(p).add(new T.Vector3(Math.cos((hour-6)/12*Math.PI)*150,Math.max(20,Math.abs(l.altitude)*180),-65));sun.target.position.copy(p);sun.target.updateMatrixWorld();renderer.toneMappingExposure=.95+l.day*.12;stars.position.copy(p);stars.material.opacity=1-l.day;stars.visible=l.day<.99;for(const light of lights)light.intensity=(1-l.day)*23;lampMaterial.color.set(l.day>.5?'#eee3be':'#ffcf7d');}};
}
