import {createLandmarks} from './landmarks.js';
import {nearbyPool,poolAt,poolHeight} from './swimming.js';
import {createFacilities} from './facilities.js';
import * as THREE from '../vendor/three.module.js';
import {createWorld} from './world.js';
import {createPlayer} from './player.js';
import {Ambience} from './audio.js';
import {configureGeography,mapData,groundHeight,walkHeight,BASE_ELEVATION,nearestRoad} from './geography.js';
import {createStreetLife} from './street-life.js';
import {loadFerrari} from './ferrari.js';
import {createMobility,createCats} from './mobility.js';
import {createAtmosphere} from './atmosphere.js';
import {createMapUI} from './map-ui.js';
const [map,elevation]=await Promise.all(['./data/arad-map.json','./data/elevation.json'].map(async path=>{const r=await fetch(path);if(!r.ok)throw Error('Missing geographic data: '+path);return r.json();}));configureGeography(map,elevation);
const canvas=document.querySelector('#world'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(Math.max(devicePixelRatio,1.5),2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e9d6b4');scene.fog=new THREE.Fog('#e8d7b9',2800,14500);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.15,30000);const ambient=new THREE.HemisphereLight('#e1eef2','#c9a87b',1.7);scene.add(ambient);
const sunlight=new THREE.DirectionalLight('#ffe6bd',2.5);sunlight.position.set(-90,160,-100);sunlight.castShadow=true;sunlight.shadow.mapSize.set(4096,4096);Object.assign(sunlight.shadow.camera,{left:-80,right:80,top:80,bottom:-80,near:1,far:420});sunlight.shadow.normalBias=.05;sunlight.shadow.bias=-.00008;sunlight.shadow.radius=2;scene.add(sunlight,sunlight.target);
const world=createWorld(scene),facilities=createFacilities(scene,world),landmarks=createLandmarks(scene,world),player=createPlayer(scene,canvas,camera,world.colliders,world.spawn),ambience=new Ambience();
const wakeGeometry=new THREE.RingGeometry(.62,.69,40);wakeGeometry.rotateX(-Math.PI/2);const wakes=Array.from({length:2},()=>{const mesh=new THREE.Mesh(wakeGeometry,new THREE.MeshBasicMaterial({color:'#ddfaff',transparent:true,opacity:.3,depthWrite:false,side:THREE.DoubleSide}));scene.add(mesh);return mesh;});
const contactGeometry=new THREE.CircleGeometry(.38,20);contactGeometry.rotateX(-Math.PI/2);const contactBase=contactGeometry.attributes.position.array.slice();const contactShadow=new THREE.Mesh(contactGeometry,new THREE.MeshBasicMaterial({color:'#66503a',transparent:true,opacity:.19,depthWrite:false}));contactShadow.frustumCulled=false;scene.add(contactShadow);
function updateContactShadow(){const p=player.group.position,floor=walkHeight(p.x,p.z),base=groundHeight(p.x,p.z),a=contactGeometry.attributes.position;for(let i=0;i<a.count;i++){const x=p.x+contactBase[i*3],z=p.z+contactBase[i*3+2];a.setXYZ(i,x,floor+groundHeight(x,z)-base+.025,z);}a.needsUpdate=true;contactShadow.material.opacity=.2*Math.max(0,1-(p.y-floor)/2);}
const help=document.querySelector('#help'),mapDialog=document.querySelector('#map-dialog');let overview=false;
function syncInput(){const paused=help.open||mapDialog.open||overview;player.setBlocked(paused||mobility.driving);mobility.pause(paused);}
function showHelp(){help.showModal();syncInput();}function showMap(){mapDialog.showModal();syncInput();mapUI.update(player.group.position,player.yaw);}
document.querySelector('#info').onclick=showHelp;document.querySelector('#open-map').onclick=showMap;document.querySelector('#mini-map-button').onclick=showMap;
document.querySelector('#close-help').onclick=()=>help.close();document.querySelector('#explore').onclick=()=>help.close();document.querySelector('#close-map').onclick=()=>mapDialog.close();
for(const dialog of [help,mapDialog])dialog.addEventListener('close',()=>{syncInput();canvas.focus({preventScroll:true});});
document.querySelector('#dismiss').onclick=()=>{document.querySelector('#instructions').hidden=true;canvas.focus({preventScroll:true});};
let toastTimer;function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),6000);}
function setOverview(value){overview=value;document.querySelector('#overview').setAttribute('aria-pressed',String(value));document.querySelector('#overview-hint').hidden=!value;syncInput();if(!value&&!mobility.driving)player.travelTo([player.group.position.x,player.group.position.z],player.yaw);canvas.focus({preventScroll:true});}
document.querySelector('#overview').onclick=()=>setOverview(!overview);
const mapUI=createMapUI(world.destinations,d=>{if(mobility.driving){toast("צאו מהרכב לפני מעבר למקום אחר");return;}mapDialog.close();setOverview(false);player.travelTo(d.arrival,d.bearing);mobility.summon();toast(d.name+' — '+d.text);updateLocation();});
const soundButton=document.querySelector('#sound');soundButton.onclick=async()=>{try{const enabled=await ambience.toggle();soundButton.setAttribute('aria-pressed',String(enabled));soundButton.setAttribute('aria-label',enabled?'כיבוי צלילי סביבה':'הפעלת צלילי סביבה');}catch{toast('צלילי הסביבה אינם זמינים בדפדפן הזה.');}canvas.focus({preventScroll:true});};
let colorIndex=0;const shirtColors=['#f1e8c8','#b7caba','#d9b1a0','#bac5dc','#d3bbd8'];document.querySelector('#palette').onclick=()=>{colorIndex=(colorIndex+1)%shirtColors.length;player.materials.shirt.color.set(shirtColors[colorIndex]);document.querySelector('.swatch').style.background=shirtColors[colorIndex];canvas.focus({preventScroll:true});};
window.addEventListener('keydown',e=>{if(e.repeat)return;if(e.code==='Tab'&&!help.open){if(!mapDialog.open){e.preventDefault();showMap();}return;}if(help.open||mapDialog.open)return;if(e.code==='KeyH'){e.preventDefault();showHelp();}if(e.code==='KeyM')soundButton.click();if(e.code==='KeyV')setOverview(!overview);});
const ferrari=await loadFerrari(renderer);
const mobility=createMobility(scene,world,player,camera,canvas,toast,ferrari),cats=createCats(scene,world),atmosphere=createAtmosphere(scene,world,renderer,sunlight,ambient),streetLife=createStreetLife(scene,world);
const swimButton=document.createElement('button');swimButton.id='swim-action';swimButton.textContent='כניסה למים · B';swimButton.hidden=true;document.querySelector('#vehicle-action').parentElement.append(swimButton);
function swimAction(){if(help.open||mapDialog.open||overview||mobility.driving)return;if(player.toggleSwim())toast(player.swimming?'שוחים עם מקשי התנועה · B ליציאה ליד שפת הבריכה':'יצאתם מהמים');canvas.focus();}
swimButton.onclick=swimAction;window.addEventListener('keydown',e=>{if(e.code==='KeyB'&&!e.repeat&&!e.target.closest?.('input,dialog'))swimAction();});
document.querySelector('#vehicle-action').onclick=()=>{mobility.toggle();syncInput();};document.querySelector('#summon').onclick=()=>{mobility.summon();canvas.focus();};
window.addEventListener('keydown',e=>{if(e.repeat||help.open||mapDialog.open||overview||e.target.closest?.('input,dialog'))return;if(e.code==='KeyF'){mobility.toggle();syncInput();}if(e.code==='KeyC')mobility.summon();});
let found=0;const storageKey='arad-discoveries-v1';try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(saved))for(const s of world.secrets)if(saved.includes(s.index)){s.found=true;s.g.visible=false;found++;}}catch{}
document.querySelector('#count').textContent=found;
function collect(){if(overview||help.open||mapDialog.open)return;for(const s of world.secrets){if(s.found||Math.hypot(player.group.position.x-s.x,player.group.position.z-s.z)>3.1)continue;s.found=true;s.g.visible=false;found++;document.querySelector('#count').textContent=found;toast(found===5?'כל חמשת הרגעים נמצאו. אפשר להמשיך לשוטט.':s.name+' · רגע '+found+' מתוך 5');ambience.chime();try{localStorage.setItem(storageKey,JSON.stringify(world.secrets.filter(s=>s.found).map(s=>s.index)));}catch{}}}
const namedRoads=mapData.roads.filter(r=>r.name);function updateLocation(){const p=player.group.position,r=nearestRoad(p.x,p.z,namedRoads);const place=world.destinations.find(d=>Math.hypot(d.p[0]-p.x,d.p[1]-p.z)<90);document.querySelector('#street-name').textContent=place?place.name:r.d<50?r.road.name:'בשולי המדבר';document.querySelector('#elevation-label').textContent='גובה משוער: '+Math.round(groundHeight(p.x,p.z)+BASE_ELEVATION)+' מ׳ מעל הים';}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(Math.max(devicePixelRatio,1.5),2));});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();renderer.setAnimationLoop(null);toast('התצוגה נעצרה. רעננו את הדף כדי לחזור לעיר.');});
let previous=performance.now(),elapsed=0,mapTimer=0,locationTimer=0;const overviewTarget=new THREE.Vector3(300,groundHeight(300,0),0),overviewPosition=new THREE.Vector3(3800,4500,4400);
renderer.setAnimationLoop(now=>{const dt=Math.min((now-previous)/1000,.045);previous=now;if(document.hidden)return;elapsed+=dt;if(!overview&&!mobility.driving)player.update(dt,elapsed,world.occluders);if(!overview)mobility.update(dt,elapsed);else{camera.position.lerp(overviewPosition,1-Math.exp(-dt*3));camera.lookAt(overviewTarget);}world.update(elapsed,player.group.position);facilities.update(elapsed,player.group.position);landmarks.update(Number(document.querySelector('#time').value));wakes.forEach((wake,i)=>{wake.visible=player.swimming;if(!wake.visible)return;const pool=poolAt(player.group.position.x,player.group.position.z);if(!pool)return;const phase=(elapsed*.7+i*.5)%1;wake.position.set(player.group.position.x,poolHeight(pool)+.055,player.group.position.z);wake.scale.setScalar(.5+phase*1.8);wake.material.opacity=(1-phase)*(player.moving?.35:.18);});cats.update(help.open||mapDialog.open?0:dt,elapsed,player.group.position);atmosphere.update(dt,player.group.position);streetLife.update(help.open||mapDialog.open||overview?0:dt,elapsed,player.group.position,[mobility.car.root,...mobility.traffic.map(n=>n.model.root),...landmarks.buses.map(b=>b.root)]);updateContactShadow();contactShadow.visible=!mobility.driving&&!player.swimming;swimButton.hidden=mobility.driving||!nearbyPool(player.group.position.x,player.group.position.z);swimButton.textContent=player.swimming?'יציאה מהמים · B':'כניסה למים · B';collect();document.querySelector('#compass-arrow').style.transform=`rotate(${player.yaw}rad)`;mapTimer+=dt;locationTimer+=dt;if(mapTimer>.12){mapUI.update(player.group.position,player.yaw);mapTimer=0;}if(locationTimer>.7){updateLocation();locationTimer=0;}renderer.render(scene,camera);});
updateLocation();mapUI.update(player.group.position,player.yaw);renderer.render(scene,camera);document.querySelector('#loading').hidden=true;canvas.focus({preventScroll:true});
