import * as T from '../vendor/three.module.js';
import {createTrafficCar,createGarbageTruck} from './traffic-cars.js';
import {mapData,groundHeight,walkHeight,roadClearance,roadWidth,nearestRoad,inPolygon,segmentPoint,BOUNDS} from './geography.js';
const cube=new T.BoxGeometry(1,1,1),sphere=new T.SphereGeometry(1,10,8),mats=new Map();
function material(c){if(!mats.has(c))mats.set(c,new T.MeshLambertMaterial({color:c}));return mats.get(c);}
function part(parent,c,x,y,z,w,h,d,geo=cube){const o=new T.Mesh(geo,material(c));o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
export function blockedAt(colliders,x,z,r=1){if(x<BOUNDS.minX+r||x>BOUNDS.maxX-r||z<BOUNDS.minZ+r||z>BOUNDS.maxZ-r)return true;return (colliders.query?colliders.query(x,z,r+1):colliders).some(c=>inPolygon(x,z,c.polygon)||c.polygon.some((a,i)=>segmentPoint(x,z,a,c.polygon[(i+1)%c.polygon.length]).d<r));}
export function vehicle(color='#cf734c',bus=false,buggy=false){const root=new T.Group(),body=new T.Group();root.add(body);const length=bus?9:3.7,width=bus?2.45:1.8;
 part(body,color,0,.9,0,width,.62,length);part(body,'#343c41',0,.45,0,width,.18,length+.12);
 if(buggy){part(body,color,0,1.12,1.15,1.75,.35,1.25);part(body,'#514e45',0,1.05,-.38,1.35,.25,1.25);for(const x of [-.74,.74]){part(body,'#e4dbbf',x,1.5,-.95,.09,1.4,.09);part(body,'#e4dbbf',x,2.18,-.18,.09,.09,1.6);}part(body,'#e4dbbf',0,2.18,-.95,1.55,.1,.1);part(body,'#343c41',0,1.38,.4,1.1,.1,.1);}
 else{part(body,bus?'#e8e4cc':color,0,bus?2:1.4,bus?0:-.25,width*.94,bus?1.65:.7,bus?8.1:2.15);for(const x of [-1,1])for(let z=bus?-3.1:-.8;z<(bus?3.6:.8);z+=bus?1.25:1.05)part(body,'#49656c',x*width*.48,bus?2.25:1.53,z,.035,bus?.85:.43,bus?.93:.78);part(body,'#49656c',0,bus?2.2:1.52,bus?4.07:.84,width*.8,bus?.9:.4,.04);}
 const wheels=[],steering=[];const tire=new T.CylinderGeometry(.43,.43,.28,16);tire.rotateZ(Math.PI/2);
 for(const x of [-1,1])for(const z of [-1,1]){const pivot=new T.Group();pivot.position.set(x*(width/2+.04),.45,z*(bus?2.9:1.14));root.add(pivot);const wheel=part(pivot,'#323639',0,0,0,1,1,1,tire);part(wheel,'#d0c8b1',x*.15,0,0,.035,.43,.43,sphere);wheels.push(wheel);if(z===1)steering.push(pivot);}
 const lamps=[];for(const x of [-.61,.61]){const lamp=part(body,'#fff0c0',x,.96,length/2+.02,.31,.22,.055);lamp.material=new T.MeshBasicMaterial({color:'#ffecc0'});lamps.push(lamp);part(body,'#aa4034',x,.92,-length/2-.02,.3,.16,.055);}
 return {root,body,wheels,steering,length,lamps};}
export function buildRoutes(roads){const edges=[],out=new Map(),key=p=>p.map(v=>v.toFixed(2)).join(',');for(const r of roads){if(!['primary','secondary','tertiary','residential','service','unclassified','trunk'].includes(r.kind))continue;for(let i=1;i<r.p.length;i++){const a=r.p[i-1],b=r.p[i],length=Math.hypot(b[0]-a[0],b[1]-a[1]);if(length<.1||length>1000)continue;for(const reverse of (r.oneway?[false]:[false,true])){const from=reverse?b:a,to=reverse?a:b,e={from,to,length,road:r,reverse};e.start=key(from);e.end=key(to);edges.push(e);if(!out.has(e.start))out.set(e.start,[]);out.get(e.start).push(e);}}}return {edges,out};}
export function stepCar(state,input,dt,colliders){const oldSpeed=state.speed,accel=input.throttle*11;state.speed+=accel*dt;state.speed*=Math.exp(-dt*(input.brake?7:input.throttle?.17:1.4));state.speed=T.MathUtils.clamp(state.speed,-8,input.boost?29:20);const oldHeading=state.heading;state.heading+=input.steer*state.speed*dt*.095*(input.brake?1.8:1);const steps=Math.max(1,Math.ceil(Math.abs(state.speed)*dt/.25));for(let i=0;i<steps;i++){const x=state.x+Math.sin(state.heading)*state.speed*dt/steps,z=state.z+Math.cos(state.heading)*state.speed*dt/steps;let blocked=false;for(const offset of [-1.4,0,1.4])if(blockedAt(colliders,x+Math.sin(state.heading)*offset,z+Math.cos(state.heading)*offset,.94))blocked=true;if(Math.abs(groundHeight(x,z)-groundHeight(state.x,state.z))>.35)blocked=true;if(blocked){state.speed=-state.speed*.16;state.heading=oldHeading;break;}state.x=x;state.z=z;}return (state.speed-oldSpeed)/dt;}
export function createMobility(scene,world,player,camera,canvas,toast,playerCar=null){
 const car=playerCar||vehicle('#d97847',false,true);scene.add(car.root);if(!playerCar)for(const x of [-.6,.6]){const light=new T.SpotLight('#ffe5a8',30,38,.55,.65,1.4);light.position.set(x,1,1.8);light.target.position.set(x,.2,25);car.root.add(light,light.target);}const state={x:0,z:0,heading:0,speed:0};let driving=false,paused=false;const keys=new Set(),touch={throttle:0,steer:0,brake:false};
 const motor=mapData.roads.filter(r=>['primary','secondary','tertiary','residential','service'].includes(r.kind));
 function summon(){if(driving)return;const p=player.group.position,r=nearestRoad(p.x,p.z,motor);let best=null;for(let radius=0;radius<55&&!best;radius+=3)for(let i=0;i<16;i++){const x=r.x+Math.cos(i*Math.PI/8)*radius,z=r.z+Math.sin(i*Math.PI/8)*radius;if(Math.hypot(x-p.x,z-p.z)>=3&&!blockedAt(world.colliders,x,z,2.4)&&roadClearance(x,z)<0){best=[x,z];break;}}if(best){state.x=best[0];state.z=best[1];state.speed=0;const segment=r.road.p.slice(1).map((b,i)=>({a:r.road.p[i],b,q:segmentPoint(state.x,state.z,r.road.p[i],b)})).sort((a,b)=>a.q.d-b.q.d)[0];state.heading=Math.atan2(segment.b[0]-segment.a[0],segment.b[1]-segment.a[1]);pose(0,0);} }
 function pose(dt,accel){car.root.position.set(state.x,walkHeight(state.x,state.z),state.z);car.root.rotation.y=state.heading;const front=groundHeight(state.x+Math.sin(state.heading)*1.3,state.z+Math.cos(state.heading)*1.3),rear=groundHeight(state.x-Math.sin(state.heading)*1.3,state.z-Math.cos(state.heading)*1.3);car.body.rotation.x=T.MathUtils.lerp(car.body.rotation.x,-Math.atan2(front-rear,2.6)+T.MathUtils.clamp(accel*.003,-.07,.07),dt?1-Math.exp(-dt*8):1);car.body.rotation.z=T.MathUtils.lerp(car.body.rotation.z,-input().steer*state.speed*.005,1-Math.exp(-dt*7));car.wheels.forEach(o=>o.rotation.x+=state.speed*dt/(car.wheelRadius||.43)*(car.wheelDirection||1));car.steering.forEach(o=>o.rotation.y=input().steer*.4);}
 function toggle(){if(paused)return;if(player.swimming){toast('צאו מהמים לפני כניסה לרכב');return false;}if(driving){if(Math.abs(state.speed)>1){toast('בלמו לפני היציאה מהרכב');return false;}let exit=null;for(const side of [1,-1])for(const distance of [2.3,3.3,4.3]){const x=state.x+Math.cos(state.heading)*distance*side,z=state.z-Math.sin(state.heading)*distance*side;if(!blockedAt(world.colliders,x,z,.5)){exit=[x,z];break;}}if(!exit){toast('אין מקום פנוי ליציאה כאן');return false;}driving=false;keys.clear();player.setBlocked(false);player.travelTo(exit,state.heading+Math.PI);}
 else{if(player.group.position.distanceTo(car.root.position)>5){toast('התקרבו לפרארי האדומה, או לחצו על ״הרכב אליי״');return false;}driving=true;keys.clear();player.setBlocked(true);toast('WASD / חצים לנהיגה · Shift האצה · רווח בלימה · F יציאה');}canvas.focus();return true;}
 function input(){return {throttle:(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+touch.throttle,steer:(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')?1:0)+touch.steer,brake:keys.has('Space')||touch.brake,boost:keys.has('ShiftLeft')||keys.has('ShiftRight')};}
 window.addEventListener('keydown',e=>{if(!driving||paused||e.target.closest?.('input,dialog,button'))return;if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='KeyR'){state.speed=0;driving=false;summon();driving=true;}});window.addEventListener('keyup',e=>keys.delete(e.code));const clear=()=>{keys.clear();touch.throttle=touch.steer=0;touch.brake=false;};window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);
 for(const el of document.querySelectorAll('[data-drive]')){const [field,value]=el.dataset.drive.split(':');el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);touch[field]=field==='brake'?true:Number(value);});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,()=>touch[field]=field==='brake'?false:0);}
 const graph=buildRoutes(motor),traffic=[];let random=123;const rand=()=>((random=Math.imul(random,1664525)+1013904223>>>0)/4294967296);
 for(let i=0;i<42;i++){const model=i%7===0?vehicle('#e9dfc8',true):i%11===1?createGarbageTruck(car.environment):createTrafficCar((i-Math.floor(i/7)-1)%7,['#e9e9e5','#b6bec6','#343940','#f3f1e9','#254976','#8b2637'][i%6],car.environment);scene.add(model.root);const dest=world.destinations[i%world.destinations.length],near=graph.edges.filter(e=>Math.hypot(e.from[0]-dest.arrival[0],e.from[1]-dest.arrival[1])<420&&(i%7!==0||roadWidth(e.road)>=8)),pool=near.length?near:graph.edges;traffic.push({model,edge:pool[Math.floor(rand()*pool.length)],clock:i,travel:rand()*pool[Math.floor(rand()*pool.length)].length*.1,speed:i%7===0?7:10});}
 const terminalEdges=graph.edges.filter(e=>Math.hypot(e.from[0]+135,e.from[1]-300)<130&&roadWidth(e.road)>=8);for(let i=0;i<4&&terminalEdges.length;i++){const model=vehicle(i%2?'#83aaa0':'#c3d1cc',true),edge=terminalEdges[Math.floor(i*terminalEdges.length/4)];scene.add(model.root);traffic.push({model,edge,clock:i*6,travel:Math.min(edge.length-.2,i*5),speed:5.5});}
 function updateTraffic(dt,p){for(const npc of traffic){let e=npc.edge;const gap=car.root.position.distanceTo(npc.model.root.position);const nearPlayer=npc.model.root.position.distanceTo(player.group.position)<5;npc.clock+=dt;npc.model.updateVisuals?.(dt);let move=gap<7||nearPlayer||npc.model.shouldPause?.(npc.clock)?0:npc.speed*dt;npc.travel+=move;while(npc.travel>e.length){npc.travel-=e.length;const all=graph.out.get(e.end)||[],choices=all.filter(n=>n.end!==e.start&&(npc.model.length<8||roadWidth(n.road)>=8));const next=(choices.length?choices:all);if(!next.length){npc.travel=e.length;break;}e=npc.edge=next[Math.floor(rand()*next.length)];}const t=Math.min(1,npc.travel/e.length),dx=(e.to[0]-e.from[0])/e.length,dz=(e.to[1]-e.from[1])/e.length,offset=Math.min(roadWidth(e.road)*.22,1.9)*Math.min(1,npc.travel/4,(e.length-npc.travel)/4),x=e.from[0]+dx*npc.travel-dz*offset,z=e.from[1]+dz*npc.travel+dx*offset;npc.model.root.position.set(x,walkHeight(x,z),z);npc.model.root.rotation.y=Math.atan2(dx,dz);npc.model.body.rotation.x=-Math.atan2(groundHeight(x+dx,z+dz)-groundHeight(x-dx,z-dz),2);npc.model.root.visible=Math.hypot(x-p.x,z-p.z)<900;npc.model.wheels.forEach(w=>w.rotation.x+=move/(npc.model.wheelRadius||.43));}}
 summon();const seat=new T.Vector3(),desired=new T.Vector3(),target=new T.Vector3();
 return {car,state,traffic,toggle,summon,get driving(){return driving;},pause(value){paused=value;if(value)clear();},update(dt,t){if(driving){const accel=stepCar(state,paused?{throttle:0,steer:0,brake:true}:input(),dt,world.colliders);for(const n of traffic)if(car.root.position.distanceTo(n.model.root.position)<(n.model.length/2+1.7)){state.speed*=Math.exp(-dt*14);}pose(dt,accel);if(car.driverSeat){car.root.updateMatrixWorld(true);car.driverSeat.getWorldPosition(seat);}else seat.set(state.x-Math.sin(state.heading)*.3,car.root.position.y+.18,state.z-Math.cos(state.heading)*.3);player.setSeated(seat,state.heading,car.driverScale||1);target.set(state.x,car.root.position.y+1.5,state.z);desired.set(state.x-Math.sin(state.heading)*9,car.root.position.y+4.8,state.z-Math.cos(state.heading)*9);desired.y=Math.max(desired.y,groundHeight(desired.x,desired.z)+1);const ray=new T.Ray(target,new T.Vector3().subVectors(desired,target).normalize());let distance=target.distanceTo(desired);for(const c of world.colliders.query(target.x,target.z,12)){const hit=ray.intersectBox(new T.Box3(new T.Vector3(c.x-c.w/2,c.minY,c.z-c.d/2),new T.Vector3(c.x+c.w/2,c.maxY,c.z+c.d/2)),new T.Vector3());if(hit){const d=target.distanceTo(hit)-.5;if(d>2)distance=Math.min(distance,d);}}desired.copy(ray.direction).multiplyScalar(distance).add(target);camera.position.lerp(desired,1-Math.exp(-dt*4));camera.lookAt(target);}car.updateVisuals?.(input(),Math.max(0,Math.sin((Number(document.querySelector("#time").value)-6)/12*Math.PI)));updateTraffic(paused?0:dt,player.group.position);document.querySelector('#vehicle-action').textContent=driving?'יציאה מהרכב · F':'כניסה לרכב · F';document.querySelector('#speed').textContent=driving?Math.round(Math.abs(state.speed)*3.6)+' קמ״ש':'';document.body.classList.toggle('driving',driving);}};
}
export function createCats(scene,world){const cats=[];let seed=553;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);for(let i=0;i<35;i++){const d=world.destinations[i%5],base=d.arrival;let p=null;for(let j=0;j<160;j++){const a=rand()*Math.PI*2,r=4+rand()*35,x=base[0]+Math.cos(a)*r,z=base[1]+Math.sin(a)*r;if(roadClearance(x,z)>.6&&!blockedAt(world.colliders,x,z,.5)){p=[x,z];break;}}if(!p)continue;const root=new T.Group(),color=['#b78352','#676d70','#ded1b8','#444747'][i%4];scene.add(root);part(root,color,0,.38,0,.23,.2,.4,sphere);part(root,color,0,.57,.34,.2,.19,.19,sphere);for(const x of [-.12,.12]){const ear=part(root,color,x,.77,.34,1,1,1,new T.ConeGeometry(.1,.2,3));ear.rotation.x=-.1;part(root,'#d4cb83',x*.65,.61,.507,.032,.032,.019,sphere);}const legs=[];for(const x of [-.13,.13])for(const z of [-.24,.22])legs.push(part(root,color,x,.18,z,.075,.32,.075));const tail=part(root,color,0,.56,-.44,.075,.57,.075);tail.rotation.x=-.65;root.position.set(p[0],walkHeight(...p),p[1]);cats.push({root,legs,tail,home:p,heading:rand()*6.28,timer:rand()*3,walking:true});}
 return {cats,update(dt,t,player){for(const c of cats){c.root.visible=c.root.position.distanceTo(player)<180;if(!c.root.visible)continue;c.timer-=dt;if(c.timer<0){c.timer=1+rand()*4;c.walking=rand()>.3;c.heading+=(rand()-.5)*2;}const p=c.root.position;if(Math.hypot(p.x-c.home[0],p.z-c.home[1])>20)c.heading=Math.atan2(c.home[0]-p.x,c.home[1]-p.z);if(p.distanceTo(player)<2)c.heading=Math.atan2(p.x-player.x,p.z-player.z);const x=p.x+Math.sin(c.heading)*dt*.85,z=p.z+Math.cos(c.heading)*dt*.85;if(c.walking&&roadClearance(x,z)>.5&&!blockedAt(world.colliders,x,z,.35))p.set(x,walkHeight(x,z),z);else c.heading+=dt*2;c.root.rotation.y=c.heading;c.legs.forEach((leg,i)=>leg.rotation.x=c.walking?Math.sin(t*9+(i%3)*Math.PI)*.35:0);c.tail.rotation.z=Math.sin(t*2)*.2;}}};}
