import * as T from '../vendor/three.module.js';
import {mapData,groundHeight,walkHeight,roadClearance,nearestRoad,roadWidth,inPolygon,segmentPoint,BOUNDS} from './geography.js';
import {blockedAt} from './mobility.js';
const cube=new T.BoxGeometry(1,1,1),materials=new Map();
function mat(color){if(!materials.has(color))materials.set(color,new T.MeshLambertMaterial({color}));return materials.get(color);}
function part(group,color,x,y,z,w,h,d,geo=cube){const o=new T.Mesh(geo,typeof color==='string'?mat(color):color);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=o.receiveShadow=true;group.add(o);return o;}
export function findPavement(world,point,clearance=.45,max=12){for(let r=0;r<=max;r+=.8)for(let i=0;i<(r?16:1);i++){const a=i*Math.PI/8,x=point[0]+Math.cos(a)*r,z=point[1]+Math.sin(a)*r;if(roadClearance(x,z)>clearance&&!blockedAt(world.colliders,x,z,.55))return [x,z];}return null;}
export function createStreetLife(scene,world){
 let seed=7123;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);const root=new T.Group();scene.add(root);const stops=[],lamps=[],people=[];const motor=mapData.roads.filter(r=>['residential','primary','secondary','tertiary','unclassified'].includes(r.kind));
 function label(name,ref,parent){if(typeof document==='undefined'||!document.createElement)return;const c=document.createElement('canvas');c.width=512;c.height=160;const ctx=c.getContext('2d');if(!ctx)return;ctx.fillStyle='#165889';ctx.fillRect(0,0,512,160);ctx.fillStyle='#ffffff';ctx.font='bold 42px Arial';ctx.textAlign='center';ctx.direction='rtl';ctx.fillText(name,256,62,480);ctx.font='30px Arial';ctx.fillText('תחנה '+ref+'  •  אוטובוס',256,125,470);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const sign=new T.Mesh(new T.PlaneGeometry(1.3,.41),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));sign.position.set(0,2.36,.055);parent.add(sign);}
 for(const stop of mapData.busStops||[]){const p=findPavement(world,stop.p);if(!p)continue;const r=nearestRoad(...p,motor),group=new T.Group();group.position.set(p[0],walkHeight(...p),p[1]);group.rotation.y=Math.atan2(r.x-p[0],r.z-p[1]);root.add(group);part(group,'#727e82',0,1.22,0,.065,2.44,.065);part(group,'#165889',0,2.36,0,1.34,.45,.075);label(stop.name,stop.ref,group);
 // Shelter shapes are illustrative where OSM does not record shelter furniture.
 const shelter=stop.shelter!=='no'&&(stop.shelter==='yes'||stop.id%3===0);let free=shelter;for(const x of [-1.8,1.8])for(const z of [-1.9,-.3]){const px=p[0]+Math.cos(group.rotation.y)*x+Math.sin(group.rotation.y)*z,pz=p[1]-Math.sin(group.rotation.y)*x+Math.cos(group.rotation.y)*z;if(blockedAt(world.colliders,px,pz,.3)||roadClearance(px,pz)<.25)free=false;}
 if(free){for(const x of [-1.7,1.7])part(group,'#59696c',x,1.22,-1.6,.075,2.44,.075);part(group,'#c9c5b8',0,2.52,-1,3.65,.14,1.8);part(group,'#849da0',0,1.4,-1.66,3.3,1.5,.04);part(group,'#798c8e',0,.46,-1.25,2.7,.1,.43);for(const x of [-1,1])part(group,'#59696c',x,.23,-1.25,.07,.46,.3);}
 stops.push({...stop,arrival:p,group,shelter:free});}
 const bulbMat=new T.MeshBasicMaterial({color:'#d0d4ca'}),lampGeo=new T.CylinderGeometry(.055,.10,6,8),lampRoot=new T.Group();root.add(lampRoot);
 const candidates=(mapData.streetLamps||[]).map(l=>({...l,mapped:true}));for(const r of motor){if(!['primary','secondary','tertiary'].includes(r.kind))continue;let walked=0;for(let i=1;i<r.p.length;i++){const a=r.p[i-1],b=r.p[i],length=Math.hypot(b[0]-a[0],b[1]-a[1]);if(length<.1)continue;for(let s=45-walked;s<length;s+=45){const off=roadWidth(r)/2+1,x=a[0]+(b[0]-a[0])*s/length-(b[1]-a[1])/length*off,z=a[1]+(b[1]-a[1])*s/length+(b[0]-a[0])/length*off;candidates.push({p:[x,z],mapped:false});}walked=(walked+length)%45;}}
 for(const lamp of candidates){const p=findPavement(world,lamp.p,.4,lamp.mapped?7:2);if(!p||lamps.some(l=>Math.hypot(l.p[0]-p[0],l.p[1]-p[1])<15))continue;const road=nearestRoad(...p,motor),angle=Math.atan2(road.x-p[0],road.z-p[1]),g=new T.Group(),y=walkHeight(...p);g.position.set(p[0],y,p[1]);g.rotation.y=angle;lampRoot.add(g);part(g,'#6b7476',0,3,0,1,1,1,lampGeo);part(g,'#6b7476',0,5.94,.55,.08,.09,1.2);part(g,'#505d64',0,5.9,1.12,.4,.12,.76);part(g,bulbMat,0,5.83,1.12,.3,.025,.56);lamps.push({p,y:y+5.7,mapped:lamp.mapped});}
 // Instanced streetlights keep hundreds of poles inexpensive.
 lampRoot.updateMatrixWorld(true);const batches=new Map();lampRoot.traverse(o=>{if(!o.isMesh)return;const key=o.geometry.uuid+o.material.uuid;if(!batches.has(key))batches.set(key,[]);batches.get(key).push(o);});for(const list of batches.values()){const batch=new T.InstancedMesh(list[0].geometry,list[0].material,list.length);list.forEach((o,i)=>{batch.setMatrixAt(i,o.matrixWorld);o.removeFromParent();});batch.castShadow=batch.receiveShadow=true;batch.computeBoundingSphere();root.add(batch);}
 const pool=Array.from({length:6},()=>{const light=new T.PointLight('#ffd599',0,20,2);scene.add(light);return light;});
 const headGeo=new T.SphereGeometry(1,10,8),limbGeo=new T.CapsuleGeometry(.075,.48,3,7);for(let i=0;i<90+(world.crowdHomes?.length?190:0);i++){const zone=i<170?'zim':i<210?'mall':i<245?'station':'park',zoneHomes=i>=90?world.crowdHomes.filter(h=>h.zone===zone):[],crowd=i>=90?(zoneHomes.length?zoneHomes:world.crowdHomes)[(i-90)%(zoneHomes.length||world.crowdHomes.length)]:null;const home=crowd?crowd.p:i<world.destinations.length?world.destinations[i].arrival:(stops[i%Math.max(1,stops.length)]?.arrival||world.spawn),p=findPavement(world,[home[0]+(rand()-.5)*(crowd?24:12),home[1]+(rand()-.5)*(crowd?24:12)],.5,18);if(!p)continue;const g=new T.Group(),scale=.92+rand()*.15;g.scale.setScalar(scale);g.position.set(p[0],walkHeight(...p),p[1]);root.add(g);const shirt=['#507a8b','#ab7460','#dfc888','#778a68','#d8d7c8','#5f6572'][i%6],skin=['#c7a27c','#ad805d','#d7b697','#8d6249'][i%4],pants=['#374654','#676357','#56606b'][i%3];part(g,shirt,0,1.10,0,.39,.52,.24);part(g,skin,0,1.59,0,.14,.19,.14,headGeo);part(g,['#4a4037','#77726b','#302b28'][i%3],0,1.72,-.014,.145,.08,.145,headGeo);const arms=[],legs=[];for(const side of [-1,1]){const leg=new T.Group();leg.position.set(side*.11,.84,0);g.add(leg);part(leg,pants,0,-.37,0,1,1.12,1,limbGeo);part(leg,'#373b3d',0,-.78,.04,.14,.10,.25);legs.push(leg);const arm=new T.Group();arm.position.set(side*.25,1.33,0);g.add(arm);part(arm,shirt,0,-.24,0,.8,.82,.8,limbGeo);part(arm,skin,0,-.52,0,.07,.09,.07,headGeo);arms.push(arm);}people.push({g,arms,legs,zone:crowd?.zone||"city",home:p,heading:rand()*6.28,phase:rand()*6.28,timer:rand()*5,speed:.65+rand()*.65,walking:i%4!==0});}
 let lightTimer=0;return {stops,lamps,people,update(dt,t,player,vehicles=[]){const hour=Number(document.querySelector('#time')?.value??16),night=1-T.MathUtils.smoothstep(Math.sin((hour-6)/12*Math.PI),-.12,.25);bulbMat.color.set(night>.2?'#ffe4a6':'#d0d4ca');lightTimer-=dt;if(lightTimer<=0){lightTimer=.6;const near=lamps.filter(l=>Math.hypot(l.p[0]-player.x,l.p[1]-player.z)<65).sort((a,b)=>Math.hypot(a.p[0]-player.x,a.p[1]-player.z)-Math.hypot(b.p[0]-player.x,b.p[1]-player.z));pool.forEach((light,i)=>{light.userData.active=!!near[i];if(near[i])light.position.set(near[i].p[0],near[i].y,near[i].p[1]);});}pool.forEach(l=>l.intensity=l.userData.active?night*45:0);for(const stop of stops)stop.group.visible=Math.hypot(stop.arrival[0]-player.x,stop.arrival[1]-player.z)<230;for(const npc of people){const p=npc.g.position;npc.g.visible=p.distanceTo(player)<180;if(!npc.g.visible)continue;npc.timer-=dt;if(npc.timer<0){npc.timer=2+rand()*6;npc.walking=rand()>.22;npc.heading+=(rand()-.5)*1.5;}if(Math.hypot(p.x-npc.home[0],p.z-npc.home[1])>22)npc.heading=Math.atan2(npc.home[0]-p.x,npc.home[1]-p.z);const avoid=p.distanceTo(player)<1.6||vehicles.some(v=>Math.hypot(v.position.x-p.x,v.position.z-p.z)<2.7);let moving=false;if(npc.walking&&!avoid){const x=p.x+Math.sin(npc.heading)*dt*npc.speed,z=p.z+Math.cos(npc.heading)*dt*npc.speed;if(roadClearance(x,z)>.35&&!blockedAt(world.colliders,x,z,.30)){p.set(x,walkHeight(x,z),z);moving=true;}else npc.heading+=dt*2.5;}npc.g.rotation.y=npc.heading;npc.phase+=dt*npc.speed*7;for(let i=0;i<2;i++){npc.legs[i].rotation.x=moving?Math.sin(npc.phase+i*Math.PI)*.42:0;npc.arms[i].rotation.x=moving?-Math.sin(npc.phase+i*Math.PI)*.35:0;}}}};
}
